

kakao.redirect-uri.local=http://localhost:8080/api/users/login/oauth/kakao
kakao.redirect-uri.prod=https://your-production-domain.com/api/users/login/oauth/kakao

# ??? ???
kakao.key.client-id=0744711ae7d2a0630a178acf6b5de5e7
kakao.redirect-uri=http://localhost:8080/api/users/login/oauth/kakao



# JWT ??
# Base64? ???? secret ?
jwt.secret=S2QoQ2V9JnZHMzRaNFI3QGlxSmpVc3h2YnJ6WStHeEtscDFxM0I4Zk9vNllRclM2ZldYVGVrTXh1V3c1UGc=
jwt.expiration-ms=3600000

