spring.application.name=greenmap

# db
spring.datasource.url=jdbc:mysql://localhost:3306/greenmap
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# naver news api
naver.api.client-id=BuvHrWQsrLSaDOKGc0Fm
naver.api.client-secret=Z1Z5ygMgKl
naver.api.base-url=https://openapi.naver.com

# HTTP ?? ?? ?? ??
logging.level.org.apache.coyote.http11=DEBUG
logging.level.org.apache.tomcat=DEBUG

# ?? ?? ??
logging.level.root=INFO

# WebClient ?? ??
logging.level.org.springframework.web.reactive.function.client=DEBUG
logging.level.reactor.netty.http.client=DEBUG